name: CustomGamemode
version: '1.0'
main: me.miskynet.customGamemode.Main
api-version: '1.21'
authors: [ MiSkynet ]
commands:
  testcommand:
    description: Test command for the CustomGamemode plugin